{{- if not .Values.node.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnanode.fullname" . }}-secrets
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.node.secretKey | quote }}
{{- end }}